### ISSUE TITLE
How enable function NetFx35

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#101]
Hi. How i can enabling function NetFx35 from this script?

**Comment by marcosviniciusf17** [comment]
This function has been removed for now.

**Comment by Hyperyia** [comment]
For now you can use [W10UI](https://github.com/abbodi1406/BatUtil/tree/master/W10UI) to integrated windows updates + .NET Framework 3.5, then use Optimize-Offline on your new updated image.

**Comment by DrEmpiricism** [comment]
This will be added to the next script update and will be able to be set in the config file for the -Additional switch just like how drivers, registry templates, etc. can be integrated now. It will require an ISO to be used as the source image in order to use the .NET Framework 3 payload .cab packages.

**Comment by truefriend-cz** [comment]
If use new version with enable NetFx3 on ini file and Registry Tweaks then show this error:
```
Applying Optimizations to the Offline Registry Hives.
Applying Answer File to the Image.
Applying Registry Templates to the Image.
Get-ChildItem : Cannot find path 'D:\sources\' because it does not exist.
At D:\Tmp\3_2_6_3\Optimize-Offline.ps1:1709 char:157
+ ... oved' -and (Get-ChildItem -Path "$ISOMedia\sources\sxs" -Recurse -Fil ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\sources\:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Cleaning-up the Start Menu Layout.
Post-Optimization Image Health State: [Healthy]
Saving and Dismounting Windows 10 Pro
```

My profile is extracted ISO to folder D:\Tmp\DVD and Start.cmd contain path to directly wim in sources folder.
I use this method for: Extracted original ISO form Microsoft servers and download latest image (with updates) in ESD and convert to WIM format same build version (1903). And replacing extracted iso install.wim only. After this apply your script.
DrEmpiricism, do you can change method for detecting ISO structuring? Or how i can solving this problem?

**Comment by DrEmpiricism** [comment]
It's returning an error because the source image you're using is a WIM and not an ISO. As the Changelog states, in order for NetFx3 to be integrated, an ISO needs to be used as the source image in order for Optimize-Offline to set up the appropriate variables at the start of the script. Even though you're using an already extracted ISO, the source image being passed to the script is still a WIM file so the script never sets up those variables specific to ISO source images.

Instead of extracting the ISO yourself and using the WIM as the source image, just use the ISO itself and let the script do the extracting and such. There's no need for you to extract the ISO before running the script as the script will handle the extraction, integration and new ISO creation on its own.

However that section in the script where it checks for the NetFx3 payload packages should simply bypass its integration rather than returning an error and I will change that.

**Comment by KedarWolf** [comment]
If I already integrated NetFx3 with W10UI, no need to enable the option in your script I think. Is this correct?

**Comment by KedarWolf** [comment]
Like Said, if you point the script to the ISO like in my Start.cmd it'll integrate the NetFx3.

```
@ECHO OFF
CD /D "%~dp0"

REM After setting the appropriate variables and switches, run this script as an administrator to quickly call Optimize-Offline.
REM A list of all available variables and switches can be found on Optimize-Offline's GitHub Repository.

REM Set the Optimize-Offline Source Path variable.
SET "SourcePath=D:\1\Enterprise.iso"

NET SESSION >NUL 2>&1
IF %ERRORLEVEL% NEQ 0 (
    ECHO Permission denied. This script must be run as an Administrator.
    ECHO:
    PAUSE
    EXIT
) ELSE (
    ECHO Running as Administrator.
    TIMEOUT /T 2 >NUL
    PowerShell.exe -NoProfile -ExecutionPolicy Bypass -File .\Optimize-Offline.ps1 -SourcePath "%SourcePath%" -WindowsApps "Select" -SystemApps -Packages -Features -Registry -Win32Calc -Additional -ISO
)
PAUSE
EXIT
```
