### ISSUE TITLE
ISO Creation Error.[BUG]

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#113]
`Missing the required efisys_noprompt.bin bootfile for ISO creation.`

18363.1 Enterprise ISO updated with W10UI script to 18262.10015

**Comment by DrEmpiricism** [comment]
This is not a bug with Optimize-Offline...

The reason Optimize-Offline bypasses the ISO creation is because the W10UI script removes the efisys_noprompt.bin, thus it's not present for Optimize-Offline to use as a bootcode for ISO creation.

To correct this from occurring, you need to remove that line of code in the W10UI script that deletes the efisys_noprompt.bin so your update images retain both bootcode files.

**Comment by KedarWolf** [comment]
Thank you.
