### ISSUE TITLE
Start script error [BUG]

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#121]
**Describe the bug**
Bug 1: If script running get errors and no continue.
Bug 2: Title bar show old version (3.2.6.2)

**Screenshots**
![image](https://user-images.githubusercontent.com/7845691/64270797-6ae6aa80-cf3c-11e9-9c88-a6e0da9118b4.png)

**Desktop (please complete the following information):**
 - OS being optimized: Windows 10 Pro
 - OS build: All supported

**Additional context**
Script running on Windows 7 (PowerShell installed)

**Script version**
3.2.7.0

**Comment by DrEmpiricism** [comment]
This is not a bug but working as intended. The issue is you are not meeting the prerequisite requirements to even run the script. The requirements you're not meeting are all of them considering you're trying to run this on Windows 7 which uses PowerShell version 2...

PowerShell version 5 is required by Optimize-Offline because it uses a handful of variables and parameters that were introduced in version 5. Likewise, it is a Windows 10 optimization script and not a Windows 7 optimization script, so why you're even trying to use it in a Windows 7 environment is beyond me.
