### ISSUE TITLE
[BUG] Optimize-Offline requires a 64-bit environment

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#128]
Version 3.2.7.6

If run cmd file then show error: Optimize-Offline requires a 64-bit environment
and script ended (press key...).

**Comment by tomlp999** [comment]
Hi, i am facing the same issue for 3.2.7.6, starting from Optimize-Offline.cmd or by command, with the same error for both .iso and .wim source

**Comment by Ainatar** [comment]
Same.

**Comment by Hyperyia** [comment]
Hi, i think i've found the problem - it only happens if the Optimize-Offline **3.2.7.6** is run on a foreign language (**non-English**) Windows installation.

The problem is this line in **Test-Requirements.ps1**:
![image](https://user-images.githubusercontent.com/32967354/68083018-3e5beb80-fe24-11e9-923e-319d971cabdc.png)

As you can see, the script passes only if that PowerShell command will return a "64-bit" value, but the "64-bit" value is returned only on **English language** Windows installations, while for instance my **Polish language** Windows installation returns "64-bitowy" value, instead of the "64-bit" one, and this is why the script does not start:
![image](https://user-images.githubusercontent.com/32967354/68083062-a27eaf80-fe24-11e9-9c7d-444af4a412f2.png)

**Comment by DrEmpiricism** [comment]
This has been corrected.
