### ISSUE TITLE
[QUESTION] Testing

### ISSUE THREAD

**Issue by LukasKysela** [DrEmpiricism/Optimize-Offline#130]
Developer, I want to ask before you release a version of your product, so you test it first or do you rely on it to work for people and if not, people will contact you?

**Comment by DrEmpiricism** [comment]
I would never just release something without thoroughly testing it. First off, doing so would be extremely unprofessional and selfish. And secondly, I would likely never rely on the feedback of a 3rd party.

Each time the script gets pushed to Github, it has been run on multiple VMs on my server across various Windows versions the script supports. Likewise, I am able to debug and audit logs and files client devices cannot. This does not mean every version of Optimize-Offline comes bug free because one cannot account for every runtime OS scenario, as they are completely dependent on the end-user who has installed it.
