### ISSUE TITLE
[REQUEST]Support for 1709 and below.

### ISSUE THREAD

**Issue by tharos96** [DrEmpiricism/Optimize-Offline#134]
I used an old version from your Github - 3.1.2.9 for my 1709 iso.
Unfortunately it didn't work very well.
I needed 11 broken images until I finally got 1 somewhat stripped, working ISO. (Logs attached.)
I didn't expect old versions to work flawlessly, I just wanted to let you know, if you ever decide to support 1709 and below again. 
1709 is highly demanded by people in the gaming community as it provides the best and most stable performance.
Personally I'd love to see the current script working with 1709 as it's much more refined now and it became such an outstanding script.

All of the following would cause "Why did my pc restart?" during installation:

- -Registry "Harden" would break the ISO.

- Not using "-NoSetup" would break the ISO.

- Removing almost anything else than the features I removed (see logs) would break the ISO.

These logs are from the only ISO that could be successfully installed:
[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3827916/Optimize-Offline.log)
[Registry-Optimizations.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3827917/Registry-Optimizations.log)
[WindowsFeatures.txt](https://github.com/DrEmpiricism/Optimize-Offline/files/3827918/WindowsFeatures.txt)

**Comment by DrEmpiricism** [comment]
Builds 1703 and 1709 have not been supported since early 2018 (over a year ago) and therefore no versions of Optimize-Offline have been updated since then to accommodate any of Microsoft's updates. Also, those earlier versions of Optimize-Offline also had a sister-script it would call for additional integrations/removals/tweaks.

The registry hardening option was only present for a few versions, and a copious amount of optimizations and code have been modified or removed entirely since then. Also, I never supported Optimize-Offline on the MDL forums and have no idea what versions of it were distributed/modified/etc.
