### ISSUE TITLE
[REQUEST] DefaultMediaCost modification

### ISSUE THREAD

**Issue by ImportTaste** [DrEmpiricism/Optimize-Offline#136]
Windows 10 is very persistent about installing certain things (such as GPU drivers) no matter your group policy or other registry settings. One exception is if the connection is marked as a metered connection, which is the most reliable way to get Windows not to download anything until you're ready.

The setting that governs whether or not a connection type is, by default, metered, is in the registry key  `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\DefaultMediaCost`, which lists  3G, 4G, Ethernet, and WiFi. (As well as 'Default', but this should probably be left alone as it likely governs any connection type that does not fall into the previous 4 and is just as likely not to be very easily toggled.) 3G and 4G have a value of 2, which is metered, and Ethernet and WiFi have a value of 1, which is unmetered.

So, for this purpose, Ethernet and WiFi need to be set to 2, but there's a problem here: the DefaultMediaCost registry key is owned by TrustedInstaller, and taking ownership of registry keys through the CLI is [not very intuitive](https://pastebin.com/XTPt0JSC), and it's equally as befuddling to try and give ownership back to TrustedInstaller if desired.

Right now, I'm resorting to mounting install.wim, mounting filesystem, mounting the registry hive, and doing it manually through regedit, then writing the changes to install.wim, building the ISO, and only then running Optimize-Offline.

Given how much of a pain in the ass this process is and how useful this would be to incorporate, I feel it appropriate to request this as a feature, either via the -Registry argument, or having -Additional somehow bypass TrustedInstaller protection. _(Perhaps a TrustedInstaller folder within the Registry folder, in which all .reg files contained within have their keys taken ownership of and then having their ownership given to TrustedInstaller?)_

I apologize if there's an easy way of doing this already that I'm just overlooking.

**Comment by Phatastik** [comment]
The easiest method, I think, is to convert the registry change you want to make to a 'merge style' of REG code and add each required registry change to this projects provided "Additional Tweaks.reg" 
***Example of a TrustedInstaller required reg code I add***
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DoSvc]
; Set Delivery Optimization service disabled
"Start"=dword:00000004

*** Alternative ***
Temporarily get the needed privileges to run some registry changing code. 
Use sordum.org PowerRun or GitHub NSudo to run a PowerShell script or DOS command REG ADD to make your changes. Easier and less of a hassle than the permanent changes you've described.

**Comment by ImportTaste** [comment]
I didn't realize Optimize-Offline's Additional feature bypassed the TrustedInstaller permission. I tried to do this using it once before and it didn't work. But perhaps I did something wrong. I'll have to re-review the documentation and try again.

**Comment by ImportTaste** [comment]
@Phatastik Does it have to be added to Additional Tweaks specifically? The readme in the directory said any reg file in the directory would work. I added two files to this directory and set 'RegistryTemplates' to 'True' in Config.ini:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\ReserveManager]
"ShippedWithReserves"=dword:00000000
```
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\DefaultMediaCost]
"Ethernet"=dword:00000002
"WiFi"=dword:00000002
```
While my ShippedWithReserves tweak was applied correctly, the DefaultMediaCost one was not applied.

**Comment by Phatastik** [comment]
@ImportTaste I think you're right. It sounds like you can drop your own independent *.reg. files into the RegistryTemplates folder. I've been sticking them at the end of 'Additional Tweaks.reg'

**Sorry, I wasn't 100% clear.**
I was expecting you to do a practice install into a VM machine. I wasn't expecting you to tech-ninja mount the pre-installation raw registry hive!
The reason you're seeing what you've found in the pre-installation raw registry hive is that the registry changes in the RegistryTemplates folder get applied during one of the phases of image installation. I just googled "install phase OOBE" and found a page with a bunch of pictures (https://docs.microsoft.com/en-us/windows/deployment/upgrade/troubleshoot-upgrade-errors) that might help if you're a visual learner
**The registry hive you were looking shows the default settings before installation.**  
The default "ShippedWithReserves" setting is "0." Meaning that you're intended change will not change anything!
FYI, there is some debate as to whether Microsoft will allow you to control the ShippedWithReserves setting. The only way to find out is to see what happens when they ship the next giant feature update.
**Just to be extra clear**
The Registry additions aren't "bypassing TrustedInstaller" 
The installation phase where the .reg. files in the RegistryTemplates folder get applied happens at the Trusted Installer privilege level. Think about it like the reg changes are getting applied by the TrustedInstaller "owner."  . . . But you have to actually commit to the installation to see the changes.

**Comment by ImportTaste** [comment]
What I'm saying is that the ShippedWithReserves reg file is being applied by Optimize-Offline correctly. I verified it by mounting the registry hive from the finished iso and checking.

The same is not true of the DefaultMediaCost reg file. It is not applied. If Optimize-Offline is _supposed_ to have the TrustedInstaller privilege level for applying RegistryTemplate files, then this is a bug that needs to be fixed.

**Comment by DrEmpiricism** [comment]
Registry templates that users can add to be automatically imported into the offline registry hives are not granted the token privileges required for access to protected registry keys. Only certain values applied by the script itself are granted these privileges.
