### ISSUE TITLE
Not a [BUG] i guess, just some questions regarding Explorer, OneDrive & Connect

### ISSUE THREAD

**Issue by verlain3** [DrEmpiricism/Optimize-Offline#140]
I've used this script in the past, few months ago, and i remember being able to prevent OneDrive from installing. I've tried it again today, without the fresh commits that @DrEmpiricism did 7 hours ago and OneDrive gets installed. I've searched the Optimize-Offline.ps1 and even the Additional Tweaks.reg and couldn't find anything related to it. Is this no longer integrated on the script?

Another thing that i think in the past was not present after removing WindowsApps was the "Connect" app

![connect](https://i.imgur.com/fhgNIw4.png)

not really sure, though, just want to confirm. I've removed all WindowsApps except Microsoft.Store, StorePurchaseApp & DesktopAppInstaller.

and finally, the user folders that get removed from "This PC" when using the -Registry switch appear again if we open a folder that is present on desktop, as example, or even from the start menu

![thispc](https://i.imgur.com/qVBP3sb.png)

they don't appear only when opening Explorer from the taskbar. I assume there's no way to avoid this?!

**Please complete the following information:**

- Image Name: [Windows 10 Education]
- Image Build: [18362]
- Host Environment: [Windows 10 Pro - 17134]
- Parameters Passed: [-WindowsApps "Select" -SystemApps -Capabilities -Packages -Features -Registry -ISO "Prompt"]

**Log files**
[OptimizeLogs.zip](https://github.com/DrEmpiricism/Optimize-Offline/files/3853889/OptimizeLogs.zip)

thank you in advance

**Comment by Hyperyia** [comment]
There used to be an additional online script called "Remove-OneDrive" in the Optimize-Offline repository, but @DrEmpiricism has removed it some time ago for some reason. I still have links to it:

https://github.com/DrEmpiricism/Optimize-Offline/blob/bd34011d75337a972c6c4adc87a598853792e812/Content/Additional/Setup/Remove-OneDrive.bat
https://github.com/DrEmpiricism/Optimize-Offline/blob/bd34011d75337a972c6c4adc87a598853792e812/Content/Additional/Setup/Remove-OneDrive.ps1

Get both the .bat and .ps1 files, place them on Desktop and run the Remove-OneDrive.bat as Administrator.

**Comment by verlain3** [comment]
Hey @Hyperyia, thanks for the reply. I appreciate the links but i was looking for the old behavior, to prevent OneDrive from installing in the first place rather than uninstalling it after Windows online.

Maybe we can integrate that .ps1 code into the original Optimize-Offline script?

**Comment by Phatastik** [comment]
@verlain3 
Stop OneDrive from installing by doing this one simple trick! (Click bait joke) 
But seriously, in my experience, removing a single reg key in an offline image build always prevents OneDrive from installing. What this 'trick' does is stop OneDrive from installing on it's own, but you can manually install it later if you want to.
You found the "Additional Tweaks.reg" file and may already be adding those registry changes. If so, simply add this to the bottom of that file:
```
; Remove OneDrive first run value
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
"OneDriveSetup"=-
```
What I just described is the [method I use](https://github.com/DrEmpiricism/Optimize-Offline/issues/139#issuecomment-554474864) I use to add my small set of offline reg changes. 
If you **_only_** want to remove "OneDrive first run", than you can follow the instructions in the README.md and make a fresh properly formatted '.reg' file and include it in the "Additional\RegistryTemplates" folder.

**I don't have an exact answer for your other issues**
My build Windows 10 Education Build 18363 doesn't have the "connect app". I keep one more than you (VP9VideoExtensions). You don't need to keep the "DesktopAppInstaller" since you can get it later from the [store](https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1?activetab=pivot:overviewtab) Also see this [maintained blog](https://www.vacuumbreather.com/index.php/blog/item/87-windows-10-1903-built-in-apps-what-to-keep) that shows a lists if removable apps.

All my folders look like what you show, but I'm not remembering them ever looking any differently.

**Comment by verlain3** [comment]
@Phatastik thanks for the tips

I tried your method to prevent OneDrive from installing but i'm afraid it is not working properly. After installation it is not present in the "Apps & features" from settings neither the system tray - it is present on the Start Menu though - but after 2/3 min it gets installed automatically - appearing in the system tray and in the "Apps & features".
I've tried to add the scripts @Hyperyia provided above into the "Setup" folder from the -Additional command but it didn't work.

Regarding the "Connect" app it is strange, i've tried multiple Windows installations in a VM and i always have that app installed.

Perhaps @DrEmpiricism can shed some on this

**Comment by Phatastik** [comment]
@verlain3 
That's really weird. I've done nothing else related to OneDrive other than make that single offline registry deletion for years and **_never_** had OneDrive automatically install. This approach was applied to new builds from (14393) up to and including yesterdays VM install of 1909 (18363).
I _did_ just have OneDrive install automatically on a resent test VM build, but in this case that single registry deletion was **not** performed! Which is kind-of a classic test case for my solution. If the reg key is not deleted because of some error, then OD gets installed. If I delete the reg key offline by appending the reg script shared above to the "Additional Tweaks.reg" file then OD stays dormant.
You could boot and suspender that registry deletion...
If you haven't already, activate the Setup features, See the ReadMe in Content\Additional\Setup
Add the following line of code to "OOBE.cmd"
`REG DELETE "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "OneDriveSetup" /f >NUL`

As for the "Connect" app, I've never seen it. There is an app called "Microsoft.OneConnect" that shows as removable on the blog link I shared in my last post. If you see that it's installed on your PC, try and use PowerShell to remove it.

**Comment by verlain3** [comment]
@Phatastik 
no good even with that line added into "OOBE.cmd" 
and yes, i edited "config.ini" and now "Additional.json" to activate the Setup features as well as Registry Templates. Same behavior as before

Regarding the connect app, afaik it isn't the "Microsoft.OneConnect" according to this Microsoft article: https://docs.microsoft.com/en-us/windows/application-management/apps-in-windows-10

Microsoft.OneConnect = Paid Wi-Fi & Cellular

![Untitled](https://user-images.githubusercontent.com/15094643/69096445-5babcf00-0a4c-11ea-9793-46a1a58e7a6f.png)

When i input "Get-AppxProvisionedPackage -Online | Format-Table DisplayName, PackageName" into Powershell all i get is this:

```
DisplayName                 PackageName
-----------                 -----------
Microsoft.StorePurchaseApp  Microsoft.StorePurchaseApp_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe
Microsoft.WindowsCalculator Microsoft.WindowsCalculator_2019.105.612.0_neutral_~_8wekyb3d8bbwe
Microsoft.WindowsStore      Microsoft.WindowsStore_11811.1001.1813.0_neutral_~_8wekyb3d8bbwe
```

Are you sure you don't have that app installed on your system?

**Comment by Phatastik** [comment]
@verlain3 You're own your own with "connect app" ... never seen it or heard of it before.

I will make one final stab at resolving your OneDrive issue using script code that was once included in Optimize-Offline.ps1.
Look in [Version: 3.2.5.6 from 06/14/2019](https://raw.githubusercontent.com/DrEmpiricism/Optimize-Offline/32c208f5fbff9f15904a74d18895d24c292eaa8a/Optimize-Offline.ps1) for "Disabling Microsoft OneDrive Automatic Setup and Startup"
You see a bunch of registry changes including the key removal code that I've already shared with you. Once again, I will say that that single key removal is all I've ever done and all I've ever needed.
Back to the 3.2.5.6, Don't try to just add that code back into the current script. The latest design of the Optimize-Offline script is structured differently and so you would have to change variable names and ditch all the "New-Container" code lines since those lines are now generated internally  (I think) by the library script. Plus, if you mess about with the main script you'll 'void the warranty' and can't expect any help from the developer.
What you can do is convert all the code from PowerShell to CMDShell and put it into the OOBE.cmd.
Alternatively or additionally, you can convert it into "reg-merge" code and appending to the "Additional Tweaks.reg."
It's pretty easy to make the CMDShell, so l'll pump that out and paste it below, but first I'll tell you the steps to follow so you can check my work.
Paste all the "Disabling Microsoft OneDrive Automatic Setup and Startup" code from the old script into notepad
**Get rid of all the lines with:**

- "New-Container -Path" (PowerShell only)
- "{018D5C66-4533-4307-9B53-224DE2ED1FE6}" (those registry keys relate to  [Remove OneDrive from the File Explorer Sidebar ](https://www.techjunkie.com/remove-onedrive-file-explorer-sidebar-windows-10/) which-if we're doing this right-will never appear in the first place) 
- "OneDrive.lnk"" (that effects the Start Menu link is set to effect the mounted image)
- 

**Two unique keys**

- "Remove-ItemProperty" key is identical to what I already shared

`REG DEL "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /V "OneDriveSetup" /F`

- "[Byte[]](0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00)) -Type Binary"

I cheated and used the version from the [Decrapifier, 18XX/19XX](https://community.spiceworks.com/scripts/show/4378-windows-10-decrapifier-18xx-19xx) script (which is something you may want to look a)
`REG ADD "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run" /T REG_BINARY /V "OneDrive" /D 0300000021B9DEB396D7D001 /F`

**Replace**
( -ErrorAction SilentlyContinue) with nothing (delete)
(Set-ItemProperty -Path "HKLM:\WIM_HKLM_) with (REG ADD "HKLM\)
(Set-ItemProperty -Path "HKLM:\WIM_) with (REG ADD ")
(-Name) with (/T REG_DWORD /V)
(-Value with (/D)
(-Type DWord) with (/F)

**Add below converted code to OOBE.cmd**
```
REG DEL "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /V "OneDriveSetup" /F
REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableFileSync" /D 1 /F
REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableFileSyncNGSC" /D 1 /F
REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableMeteredNetworkFileSync" /D 1 /F
REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableLibrariesDefaultSaveToOneDrive" /D 1 /F
REG ADD "HKLM\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableFileSyncNGSC" /D 1 /F
REG ADD "HKLM\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableMeteredNetworkFileSync" /D 1 /F
REG ADD "HKLM\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\OneDrive" /T REG_DWORD /V "DisableLibrariesDefaultSaveToOneDrive" /D 1 /F
REG ADD "HKCU\SOFTWARE\Microsoft\OneDrive" /T REG_DWORD /V "DisablePersonalSync" /D 1 /F
REG ADD "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run" /T REG_BINARY /V "OneDrive" /D 0300000021B9DEB396D7D001 /F 
```
Good luck!

**Comment by verlain3** [comment]
@Phatastik 
First of all, i appreciate your efforts in trying to help
Second, i need to apologize because in-between so many testings i was doing, apparently i missed something as today i reset'd everything and Onedrive does not get installed automatically BUT it does still appear in the start menu, not a big deal, i guess (maybe you can confirm if this happens to you as well?)

![Untitled](https://user-images.githubusercontent.com/15094643/69194963-62a51100-0b22-11ea-98ea-fb999f63aa40.png)

If i click on it, nothing happens and to get rid of it i open the location of the file and delete it
Again, i'm sorry @Phatastik. Nonetheless i've tried your last tips (those .reg tweaks into OOBE.cmd) and the behavior is the same, it doesn't get installed automcatically but still appears on the start menu, so there's definitely no need for those

Now, to the connect app again, if more users can say if they have it or not, i've tried everything i could think of, and the app is always there, i would appreciate it.
tyvm

**Comment by Phatastik** [comment]
Glad it's resolved. 
Yes, the onedrive link is in my start menu. 

If you think you might want to install OneDrive at some point in the future, than I would only put the single command (REG DEL "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /V "OneDriveSetup" /F) into OOBE.cmd.
You can get the  [the latest](https://www.softpedia.com/get/Internet/File-Sharing/Microsoft-SkyDrive.shtml) official version of OneDrive and install it like any other app.

**Comment by ImportTaste** [comment]
@DrEmpiricism Why did you remove the Remove-OneDrive script anyway?

**Comment by Phatastik** [comment]
@verlain3 I just stumbled on this today:
The OP in the following post claims that the PPIProjection System Application has something to do with the Connect app.
 ["Remove Connect System Application" ](https://social.technet.microsoft.com/Forums/en-US/d539880b-42bb-4b77-b2db-339f3b62fc46/remove-connect-system-application?forum=win10itprosetup)

I always remove the "Microsoft.PPIProjection" System Application as part of my Optimize process. This is possibly why I never see the Connect app in the start menu. It is the only 'extra' system app I remove beyond the list of ten recommendations found in this projects ["README.md | About System Applications" ](https://github.com/DrEmpiricism/Optimize-Offline#about-system-applications)

**Comment by verlain3** [comment]
@Phatastik 

spot on, that was it. I now remember that when i tested this script some months ago, like i stated in the OP, i always removed PPIProjection and this time i didn't touch it so makes sense in the end. Thank you one more time!

Regarding the other two "issues" i also would like to know if there was a special reason for @DrEmpiricism to drop the removal of OneDrive but that's up to him to reveal or not. I will be using the tweak shared by @Phatastik from now on which seems to work pretty good.

About the explorer issue i think there's nothing that can be done about it so i will just avoid removing those libraries from the explorer.
