### ISSUE TITLE
[REQUEST] Mount NTUSER.DAT and apply HKCU reg files to it

### ISSUE THREAD

**Issue by ImportTaste** [DrEmpiricism/Optimize-Offline#142]
`C:\Users\Default\NTUSER.DAT` houses the default settings for new users. By mounting this during the Optimize-Offline process, `.reg` files that target HKCU can be used to help define settings for all users that have no HKLM equivalent.

Commands in OOBE can only partially fulfill this function, because targeting HKCU through this script will only work for the first user created. The only alternative I can think of is mounting the registry hive during SetupComplete, but you'd of course have to make sure to alter the path to the mounted path appropriately.

Implementing this to the RegistryTemplates functionality is the best course of action, and it helps mitigate erroneous bug reports from those who don't understand the HKCU virtual key does not exist until the first user is made.

**Comment by DrEmpiricism** [comment]
The NTUSER.DAT is mounted as the Current User hive. It always has been. Modifications to the default NTUSER.DAT propagate to the online HKCU hive and also acts as a template for all new user profiles.

`('HKLM\WIM_HKCU "{0}"' -f "$InstallMount\Users\Default\NTUSER.DAT")`

Optimize-Offline simply uses the mounted hive name of 'HKCU' because in an offline state, the Current User is the NTUSER.DAT as the HKEY_CURRENT_USER hive does not resolve until the system is live. This is similar to how the HKEY_LOCAL_MACHINE\System\CurrentControlSet does not resolve until the system is in a runtime state, and then it uses the initial template of the HKEY_LOCAL_MACHINE\System\ControlSet001, which is why offline modifications to the ControlSet001 hive are propagated to the CurrentControlSet.

Both the internal applying of registry settings and registry template importing apply values appropriately - the name the hive uses when loaded is irrelevant.

**Comment by ImportTaste** [comment]
@DrEmpiricism My apologies, I searched Optimize-Offline.ps1 for NTUSER, didn't find it, so I assumed it wasn't part of the functionality. It didn't occur to me to check the Lib folder.
