### ISSUE TITLE
[REQUEST]1709 RS3 Support

### ISSUE THREAD

**Issue by gdeliana** [DrEmpiricism/Optimize-Offline#146]
**Is your feature request related to a problem? Please describe.**
It would be good to support Windows 10 16299 RS3

**Describe the solution you'd like**
All the feature removal to work

**Additional context**
Reason behind that: 1709 is considered the last version of W10 to not screw up latencies and is the best what you can get for gaming and security all together

**Comment by DrEmpiricism** [comment]
I have not had the time to sift through old Optimize-Offline scripts from 2 years ago when this build was supported, clean up and optimize the code and test it. Because of the copious amount of changes to pretty much the entire filesystem, kernel and policies between 1709 and 1803, adding support for 16299 into the current Optimize-Offline framework would add a significant amount of processing load and overhead.

That said, when I have the spare time over the holidays I will do my best to release a version specific to 16299.
