### ISSUE TITLE
[REQUEST] Support MediaCreationTool1909 ISOs

### ISSUE THREAD

**Issue by Byrkoet** [DrEmpiricism/Optimize-Offline#152]
Currently a non-script error is thrown: `WARNING: "Windows.iso" does not contain valid Windows Installation media`.

Users will mostly be downloading Windows 10 ISOs with the `MediaCreationTool1909.exe`, as that is the safest option at the moment, it seems.

I have looked for official ms urls, but they seem to have been replaced with redirects to the download tool.

**Comment by DrEmpiricism** [comment]
That's because the MediaCreationTool downloads the image(s) in .esd format. I have contemplated adding support for this before but in the past have refrained from doing so because of the time it could take to decompress the .esd to a .wim for those users who may not have the system resources for that.

Either the next version or the following version will support .esd as an image source, though.
