### ISSUE TITLE
[REQUEST] Way to insert group policies into the ISO

### ISSUE THREAD

**Issue by vhns** [DrEmpiricism/Optimize-Offline#154]
**Is your feature request related to a problem? Please describe.**
Having to manually add group policies after installing is kind of a pain. I'm not sure there is a way to do this currently but it'd be nice to have it. (A way to insert group policies directly into the ISO that is)
**Describe the solution you'd like**
Something like the registry templates dir.

**Comment by DrEmpiricism** [comment]
Group Policies cannot be added in an offline scenario unless you were to directly add the policy changes to the offline Local Machine/Current User registry hives directly, which is not a recommended way to go about keeping policy changes across devices because the GPO MMC plugin will not reflect those changes.

A better option would be to create a back-up of the Group Policy you wish to transfer (or use across devices), add them to 'Setup' and have the SetupComplete.cmd script copy the policies after the OOBE setup pass has completed. This can be done using Microsoft's LGPO.exe or Robocopy.

**Comment by vhns** [comment]
I see, thanks!
