### ISSUE TITLE
[BUG] PowerShell ISE deleted after OO

### ISSUE THREAD

**Issue by xyberdan** [DrEmpiricism/Optimize-Offline#175]
Why OO tool delete Powershell ISE from Windows? I know, that is the part of hardening of OS, but is it necessary to remove ISE? Later, there are some problems with reinstallation.

**Comment by DrEmpiricism** [comment]
Optimize-Offline does NOT remove PowerShell ISE from Windows. PowerShell ISE is now a FOD that can be SELECTED by the user to be removed either using its Capability Package or Cabinet Package. The only PowerShell variation Optimize-Offline does anything with automatically is the DISABLING of PowerShell 2.0 because it has been labeled a security risk by Microsoft, as detailed in the [ReadMe](https://github.com/DrEmpiricism/Optimize-Offline#about-the-smb1-file-sharing-protocol-and-windows-powershell-20-optional-features). Moreover, this is simply the disabling of the PowerShell 2.0 Optional Feature, which can certainly be re-enabled during runtime if so desired.

The removal of PowerShell ISE would only occur if it was selected for removal.

Later.
