### ISSUE TITLE
Automatic Screen Rotation doesn't work

### ISSUE THREAD

**Issue by elXames** [DrEmpiricism/Optimize-Offline#183]
First of, thank you very much for the work you've put into this!

The title says it all. Windows 10 has this **screen rotation lock feature for 2-in-1 laptops** - I'm using a ThinkPad Yoga. Usually the screen rotates when the device is in vertical tablet mode. But it's not happening for me anymore. I can't even find the feature... The only option is to do it manually which kinda sucks.

I've optimized **Windows 10 Home** with **Optimize-Offline version 4.0.1.1** and used the following settings:

### Configuration.json
- "SystemApps": true,
- "Capabilities": true,
- "Packages": false,
- "Features": false,
- "DeveloperMode": false,
- "WindowsStore": true,
- "MicrosoftEdge": false,
- "Win32Calc": true,
- "Dedup": true,
- "DaRT": "Setup",
- "Registry": true,

### removed System Apps
- Microsoft.MicrosoftEdge
- Microsoft.MicrosoftEdgeDevToolsClient
- Microsoft.Windows.CallingShellApp
- Microsoft.Windows.ContentDeliveryManager
- Microsoft.Windows.FileExplorer
- Microsoft.Windows.NarratorQuickStart
- Microsoft.Windows.ParentalControls
- Microsoft.Winodws.PeopleExperienceHost
- Microsoft.Windows.XGpuEjectDialog
- Microsoft.XboxGameCallableUI
- Microsoft.Windows.UndockedDevKit
- Microsoft.Windows.NcsiUwpApp

### removed Windows Capabilities
- App.StepsRecorder
- App.Support.QuickAssist
- Browser.InternetExplorer
- Hello.Face
- Hello.Face.Migration
- Media.WindowsMediaPlayer

I also edited the Whitelist (and applied it in the config file) and commented out the following registry settings:

### \Src\Public\Set-RegistryProperties.ps1
`<# $RegistryData.DisableNotifications (...) #>`
`<# $RegistryData.EnableThisPCDesktop (...) #>`
`<# $RegistryData.EnableRebootRecoveryMyPC (...) #>`

But the Whitelist nor the customized Registry properties shouldn't be the problem.

Help would be greatly appreciated!

**Comment by DrEmpiricism** [comment]
Optimize-Offline does not modify any settings based on the system type. I always make sure no registry settings are applied that only affect one system type (hence why Optimize-Offline does not automatically set power management profiles).

You say you "can't even find the feature." Previously, where was that feature available at? Also, are you optimizing an OEM Windows 10 image or is it one of Lenovo's images? I have no issues running optimized images on my ThinkPad P73, though it does not have screen rotation. However, all other hardware-specific features exclusive to the P73 work fine.

I am wondering if any of the System Applications that were removed caused this issue? I cannot personally test this since I do not use a laptop with screen rotation and there's no way to mimic this feature using virtual machines.

**Comment by elXames** [comment]
I was optimizing the .esd file of an ISO I downloaded via Media Creation Tool. FYI, I've gone through with the optimization procedure quite a few times already - each time trying out different setting to sort out wich ones I actually need. Automatic Screen Rotation worked back then. Sadly I can't recall the exact settings I used...
I will test it again with your latest release without customized settings. Then, gradually working up to my preferences to see where the error first occurred.

**Comment by elXames** [comment]
It's been quite a while. I've just recently decided to go through the registry settings again and there I found it: Under "DisableLocation" there is a setting which kind of turns the sensors off - I guess an accelerometer among others. I just commented that line out and now it works again :D
So, no flaw in your code!
