### ISSUE TITLE
Could not find item messages in ErrorLog

### ISSUE THREAD

**Issue by ghysler** [DrEmpiricism/Optimize-Offline#3]
Could not find item S:\Optimize-Offline-master\Optimize-Offline-master\OptimizeOfflineTemp_1627204548\MountOffline_1146830031\Windows\WinSxS\Backup\wow64_microsoft-windows-ui-xaml-inkcontrols_31bf3856ad364e35_10.0.17763.1_none_c9703603f13a2813_windows.ui.xaml.inkcontrols.dll_523c865d.

See attached ErrorLog and Optimize-Offline files. The path for all these files is in WinSxS\Backup folders, so probably not a real issue. No issues with installation.

This is using version 3.1.1.9. Perhaps an idea to include the version number in the error log.

[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/2476754/Optimize-Offline.log)
[ErrorLog.log](https://github.com/DrEmpiricism/Optimize-Offline/files/2476753/ErrorLog.log)

**Comment by DrEmpiricism** [comment]
This is simply an error for the final clean-up process where it recursively retrieves and removes folders from that \WinSxS\Backup directory.  Because of the wildcards used to run recursive removals of large directories, the same item can be returned to the pipe-line more than once.

In the most recent version. I decided to remove the clean-up of the \WinSxS\Backup directory, so I recommend using the latest version of the script.

**Comment by ghysler** [comment]
Understood, thanks! I will update the script.
