### ISSUE TITLE
Language preferences missing from Settings/Control Panel

### ISSUE THREAD

**Issue by ghysler** [DrEmpiricism/Optimize-Offline#5]
I actually haven't tested an untouched version of LTSC N 2019 yet, but for now I'm assuming it's related to your script: the language preferences are not available in Settings. Instead I'm redirected to the main Settings page upon selecting "Language preferences" from the Language bar in the taskbar. Also the "Clock and Region" settings in the old Control Panel applet is empty: "There are no items to display". The result is I'm not able to add or remove keyboard maps.

AFAIK, I did not remove any language related packages or features. Can you reproduce this? Perhaps one of the registry tweaks is responsible?

Version 3.1.1.9

[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/2476754/Optimize-Offline.log)
[ErrorLog.log](https://github.com/DrEmpiricism/Optimize-Offline/files/2476753/ErrorLog.log)

**Comment by DrEmpiricism** [comment]
This is because the Language Control Panel link, and Immersive Control Panel link, are set to non-visible within the script.

You can return their visibility with the following:

Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\DisallowCpl" -Name 4

Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\DisallowCpl" -Name 26

Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "SettingsPageVisibility" -Value "hide:cortana-language;cortana-moredetails;cortana-notifications;datausage;maps;network-dialup;network-mobilehotspot;easeofaccess-narrator;easeofaccess-magnifier;easeofaccess-highcontrast;easeofaccess-closedcaptioning;easeofaccess-keyboard;easeofaccess-mouse;easeofaccess-otheroptions;holographic-audio;tabletmode;typing;sync;pen;speech;findmydevice;printers;gaming-gamebar;gaming-gamemode;gaming-gamedvr;gaming-broadcasting;gaming-trueplay;gaming-xboxnetworking;phone;privacy-phonecall;privacy-callhistory;phone-defaultapps;windowsinsider;windowsdefender"

**Comment by ghysler** [comment]
I can confirm restoring the Immersive Control Panel link works. 

Restoring the Language Control Panel link however, does not seem to work for me with the provided "Remove-ItemProperty" lines. Are you sure these are the correct ones?

Also, I'm curious why you've decided to hide these items in the first place, since they are not privacy related, but concern rather basic OS functionality.

**Comment by ghysler** [comment]
Thanks. Restoring "18"="Microsoft.RegionAndLanguage" did the trick to unhide the Control Panel options for Clock and Region.

I can understand the decision to hide the redundant options (old and new Control Panel) - this really is a bad design choice by MS, and also to hide options for which the packages have been removed entirely. In my experience the Language and Region options are pretty commonly used though- i.e. changing the date/time format, changing keyboard languages. But since you are the creator of the script, that is completely up to you of course. :-)
