### ISSUE TITLE
removal of telemetry and windows update policies

### ISSUE THREAD

**Issue by chrcoluk** [DrEmpiricism/Optimize-Offline#55]
It is now known that if you disable all telemetry in windows 10 via unsupported methods, it can prevent certain windows update options from working as it seems those options are applied server side and require telemetry for the server's to honour what is configured.

Is the telemetry removal in this tool aware of this and not breaking these critical parts of telemetry?

**Comment by chrcoluk** [comment]
some info here

https://www.zdnet.com/article/how-to-take-control-of-windows-10-updates-and-upgrades-even-if-you-dont-own-a-business/

> Ironically, one Group Policy option available only in Enterprise and Education editions causes these settings to be completely ignored. If Allow Telemetry is set to 0 (that is, set to the lowest possible level), then Windows Update for Business settings have no effect.

**Comment by DrEmpiricism** [comment]
"All telemetry" is not disabled using this script.  To be frank, any script that says it can "disable all Windows 10 telemetry" is selling the end-user pipe-dreams because that is simply not possible.  It's not possible because though you can disable various Windows 10 services, devices, etc. from contacting Microsoft, Microsoft has a constant DNS regeneration processes for every server they use to contact their devices, while the DNS propagation itself is almost instantaneous, making it impossible to completely prevent all type of contact between a Microsoft device and Microsoft's servers.  Conversely, there are some Microsoft domains that have constantly changing name servers (DNS) that simply use higher integers per rotation allowing them to be blocked via hosts files, servers, etc. proactively.

Optimize-Offline's telemetry settings do not affect Windows Update.  There were a few registry settings that did in the past - in regards to declining any Windows Update metadata and the prevention of default driver downloads - but that was removed many versions ago.

Lastly, I will be adding a full GPO that I have been creating on my enterprise server.  I have not decided whether I will implement this feature into a fully automated process via the Optimize-Offline script itself, or as an additional feature available for end-users to execute on a live system

**Comment by chrcoluk** [comment]
ok sounds good, thanks
