### ISSUE TITLE
How to use this for installed system?

### ISSUE THREAD

**Issue by jaspergould** [DrEmpiricism/Optimize-Offline#59]
Hello.

How to use?

For fresh installed system.

**Comment by DrEmpiricism** [comment]
All information is available on the main page, including this:

> Does not perform any changes to an installed or live system nor can it optimize a live system.

Optimize-Offline is, as the name insinuates, an OFFLINE servicing script and cannot optimize a live installation.  The reason for offline optimizing is because no services, drivers, packages, etc. are provisioned or structured as required system dependencies like they are on a live system and as such.  This is why deployment servers create "master images" that are entirely optimized offline and then are set-up during the deployment process for specific devices.  Moreover, there are some things you simply cannot do when the system is live for reasons I've already mentioned.
