### ISSUE TITLE
Suggestion: offer registry optimization selection

### ISSUE THREAD

**Issue by ghysler** [DrEmpiricism/Optimize-Offline#6]
I really like what you're creating here! Finally a true LTSC version ;-)

One suggestion: could you possible make the registry optimizations selectable by using a pop-up window? (like with the features and packages selection). While 90% of the tweaks you apply are really useful, some of them are limiting my workflow a little too much. 
For example disabling the "Show most used apps" in the Start Menu. This option is required for populating recently used applications when using StartIsBack++. The tweak you apply also renders the setting unusable (greyed out, managed by organization), so rolling back is not easy.

**Comment by DrEmpiricism** [comment]
The next update will be incorporating the Harden set when using the -Registry parameter (it's no longer going to be a switch).  Moreover, I have migrated a lot of the more restrictive registry entries (and new ones) into that parameter set while the Default parameter set will not apply such restrictive entries.  Conclusively, the full set of values was a collaboration between many people using our Server GPOs to cross-reference every value and their respective results on a system.  None of them were just copied and pasted from the internet.

Like all scripts of this magnitude, it relies entirely on an OEM image and cannot take into account 3rd party software that may be used on the live system because it's impossible to code for.  Likewise, adding checks for 3rd party software would restrict the script for the majority of users who use it as it's designed to be used.

And making a pop-up window display to select whether to apply or skip a registry setting would be incredibly annoying for those who enjoy the automation of the script.

The setting that greys that out is a policy entry (Track_Progs) and has been removed in the latest version (not uploaded yet).  You can return it to default with:

Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "Start_TrackProgs" -Value 1

**Comment by ghysler** [comment]
Confirmed: version 3.1.2.1 no longer greys out that particular setting. Thank you.

Also, nice work on adding the Harden/Default Registry parameters. I'm currently testing both options to be able to evaluate the exact differences between them.

In my opinion a pop-up window for the registry settings does not need to be annoying at all. First of, it could be made optional. Second, selecting all settings with CTRL+A (like with Packages and Features) is easy enough. The benefit of being able to "selecting all but some", would be really helpful, for me at least.

Then again, I understand now that this script is not really suited for home use and actually targeted at organizations (it is rather unusual to be using the Enterprise LTSC N edition on a home PC in the first place :-) ). I will just have to put in some extra effort to tweak the end result to my liking. Feel free to close this issue if it's not worth your time and effort to implement this.

**Comment by DrEmpiricism** [comment]
I may have incorrectly worded - this script is entirely for home use and not for organizations.  Organizations, and even on my enterprise server, scripts like this are different because we use utilities like SCCM to deploy images and scripts generally need to accommodate that deployment process.  A script such as this can definitely work in an organization but this script was created for regular home users who just want optimized - and working - Windows images.

Furthermore, I will think a bit about what I can do with registry optimizations to afford users more control over them while the script is processing.
