### ISSUE TITLE
Can't create ISO, oscdimg tool missing?

### ISSUE THREAD

**Issue by SyRaza** [DrEmpiricism/Optimize-Offline#61]
At the end of the whole process, I get a message saying 

```
"2019-04-10T19:12:46 [ERROR]: Oscdimg premastering tool not found. Skipping ISO creation.
2019-04-10T19:12:46 [INFO]: Finalizing Optimizations.
2019-04-10T19:12:46 [INFO]: Optimize-Offline completed in [17] minutes with [1] errors.
```
I have Window ADK and the Windows PE addon for ADK installed on my system. I'm not sure what I'm missing here.

Thank you.

**Comment by DrEmpiricism** [comment]
It queries both keys in the registry that will contain the full path to the the ADK.  It does this, instead of using a static string, because many users install the ADKs on different partitions or drives. It then gets the architecture of the system Optimize-Offline is running on, joins the paths then checks if the oscdimg.exe is in its default Deployment Tools path.  If it is, it continues with the ISO creation.

As to why that error is being returned - either the full path to the ADK is not being returned by querying the registry or the oscdimg.exe is not in its proper location within the ADK directory.

You can try to query the ADK paths yourself using PowerShell:

`        $ADK_ROOT = @("HKLM:\Software\WOW6432Node\Microsoft\Windows Kits\Installed Roots", "HKLM:\Software\Microsoft\Windows Kits\Installed Roots") | ForEach-Object {
            Get-ItemProperty -LiteralPath $($_) -Name KitsRoot10 -ErrorAction Ignore | Select-Object -ExpandProperty KitsRoot10 | Where-Object { $($_) }
        }`

Then just check the $ADK_ROOT path and see if it has the ADK path assigned to it.  If so, ensure the oscdimg.exe is in its default location within the ADK directory.

**Comment by SyRaza** [comment]
I apologise in advance if I did anything wrong as I'm not familiar with this stuff. 

After copy and pasting 

`$ADK_ROOT = @("HKLM:\Software\WOW6432Node\Microsoft\Windows Kits\Installed Roots", "HKLM:\Software\Microsoft\Windows Kits\Installed Roots") | ForEach-Object { Get-ItemProperty -LiteralPath $($_) -Name KitsRoot10 -ErrorAction Ignore | Select-Object -ExpandProperty KitsRoot10 | Where-Object { $($_) } }`

into powershell that I ran as administrator. 

Nothing came up. [Here is a picture](https://i.imgur.com/Gvt5WYL.png)

I went into regedit to look at things myself, h[ere it a picture ](https://i.imgur.com/gYTyUpP.png)

I searched for oscdimg.exe in the windows kit folder and [here are the results. ](https://i.imgur.com/xAD0O7k.png)

**Comment by SyRaza** [comment]
Just wanted to give an update.

I was on windows 10 home. I formatted my laptop and installed the ltsc 2019 iso that I am trying to optimize, incase the issue was with windows 10 home.

I then downloaded and  installed adk and the pe addon. 

Still having the issue with not finding oscdimg. 

Not sure if Microsoft changed anything in the latest version of adk or what might be causing the issue, since this is a fresh install.

Is there a way to create the iso manually from the resulting folder that's created by your script?

**Comment by DrEmpiricism** [comment]
There is no path associated to the 'KitsRoot10' property in the registry then, since it does not return the full root path to the ADK.  The edition of the Windows 10 image would not be a factor.

What is the exact ADK version you installed? I would like to try it on a VM on my server to see if the property was changed. I have not tested any ADK kits above version 17663 since that is the maximum version the script fully supports right now (working on 18362 right now since that will likely be the version for the upcoming 1903 build).

**Comment by DrEmpiricism** [comment]
There is no path associated to the 'KitsRoot10' property in the registry then, since it does not return the full root path to the ADK.  The edition of the Windows 10 image would not be a factor.

What is the exact ADK version you installed? I would like to try it on a VM on my server to see if the property was changed. I have not tested any ADK kits above version 17663 since that is the maximum version the script fully supports right now (working on 18362 right now since that will likely be the version for the upcoming 1903 build).

And yes, the ISO can alternately be created adding the path manually.  At the end of the script, where it checks if the -ISO switch is present, simply replace $OSCDIMG with the full path to the Oscdimg directory like this:

`If ($ISO.IsPresent)
{
	$OSCDIMG = "Path\To\OscdimgDirectory"
	$ISOName = $($WimInfo.Edition).Replace(' ', '') + "_$($WimInfo.Build).iso"
	$ISOPath = Join-Path -Path $WorkFolder -ChildPath $ISOName
	$BootData = ('2#p0,e,b"{0}"#pEF,e,b"{1}"' -f "$($ISOMedia)\boot\etfsboot.com", "$($ISOMedia)\efi\Microsoft\boot\efisys.bin")
	$OscdimgArgs = @('-bootdata:{0}', '-u2', '-udfver102', '-l"{1}"', '"{2}"', '"{3}"' -f $BootData, $($WimInfo.Name), $ISOMedia, $ISOPath)
	$Host.UI.RawUI.WindowTitle = "Creating a Bootable Windows Installation Media ISO."
	Out-Log -Info "Creating a Bootable Windows Installation Media ISO."
	$RunOscdimg = Start-Process -FilePath "$($OSCDIMG)\oscdimg.exe" -ArgumentList $OscdimgArgs -WindowStyle Hidden -Wait -PassThru
	If ($RunOscdimg.ExitCode -eq 0) { $ISOIsCreated = $true }
	Else { Out-Log -Error "ISO creation failed. Oscdimg returned exit code: $($RunOscdimg.ExitCode)" }
}`

**Comment by SyRaza** [comment]
Thank you DrEmpricism. I'll try the alternative text.

I downloaded the latest versions from  [here](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install). I'm not sure how to check the version number itself.

Thank you again.

**Comment by DrEmpiricism** [comment]
That is the latest version it's been tested on and I have had no reported issues with the ISO creation process on workstations, laptops or servers until now. My only guess is either the KitsRoot10 property was not added to the registry, which in itself makes no sense since it puts it there specifically so other Microsoft services and products can query it for the ADK root path.

**Comment by jimserio** [comment]
I hate to resurrect this but I have also posted about this awhile back. The problem still exists in the latest version of Optimize Offline and Windows 1803 Pro (with OSCD installed to default location).  Removing one of the paths fixes the problem. 

$ADK_ROOT = @("HKLM:\Software\WOW6432Node\Microsoft\Windows Kits\Installed Roots") | ForEach-Object {

Any chance to maybe make the OSCDIMG a variable in Start.cmd?
