### ISSUE TITLE
Compress install.wim to install.esd

### ISSUE THREAD

**Issue by Hyperyia** [DrEmpiricism/Optimize-Offline#64]
Will you add a CLI switch in the future to compress the image to install.esd at the end?
For example NTLite has an option to compress to .esd

**Comment by DrEmpiricism** [comment]
I have considered it for a while, but have hesitated implementing it because of the length of time it can take.

I may implement something identical to what my Pro for Workstation conversion executable does and displays a selectable Windows Form Input Box where a user can select between 'Fast,' 'Maximum,' 'Solid (esd),' or 'None.'

**Comment by KedarWolf** [comment]
That would be awesome to implement that!

Not really an issue for me as without it as selecting a single Windows image in the script from the W10UI ISO my Optimize Offline ISO is small enough that I can create a USB with Rufus using FAT32 without an additional partition on the 8GB USB but if someone wants to use a 4GB Windows install USB or choosing multiple images from the ISO it would be quite helpful.  

My OCD hurts when I make an install USB that has to be NTFS and needs an additional partition.
