### ISSUE TITLE
Error With LTSC 2019.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#7]
Latest version when you try to run it on LTSC 2019 with '.\Optimize-Offline.ps1 -ImagePath "C:\en_windows_10_enterprise_ltsc_2019_x64_dvd_74865958.iso" -Build 17763 -SystemApps -Packages -Registry -NetFx3 $true' you get a message about an error on a registry entry in the script.

"D:\Optimize-Offline-master\Optimize-Offline-master\Optimize-Offline.ps1 : Missing an argument for parameter
'Registry'. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo          : InvalidArgument: (:) [Optimize-Offline.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId :  #MissingArgument,Optimize-Offline.ps1"

**Comment by DrEmpiricism** [comment]
This is why there's a ChangeLog detailing each build's updates and/or changes.  Not to mention the error code itself "Missing an argument for parameter 'Registry'. Specify a parameter of type 'System.String' and try again" tells you exactly what the problem is.

-Registry is no longer a switch but a parameter that accepts two parameter sets: Default and Harden.

[ChangeLog](https://github.com/DrEmpiricism/Optimize-Offline/blob/master/ChangeLog.md)
