### ISSUE TITLE
Error - Start-Process : Cannot convert 'System.Object[]

### ISSUE THREAD

**Issue by Radagast** [DrEmpiricism/Optimize-Offline#80]
Hi. I'm encountering an issue when creating the ISO. The full error is:

```
Start-Process : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'FilePath'.
Specified method is not supported.
At D:\winwork\Optimize-Offline.ps1:2450 char:47
+         $RunOscdimg = Start-Process -FilePath $Oscdimg -ArgumentList  ...
+                                               ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-Process], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.StartProcessCommand

ISO creation failed. Oscdimg returned exit code:
Finalizing Optimizations.
Optimize-Offline completed in [23] minutes with [1] errors.
```

I'm using the version downloaded from https://github.com/DrEmpiricism/Optimize-Offline.git and I'm trying to customise a 1903-18362.1 iso.

I have the ADK install in the default location and I've rebooted.

Thanks

Edit: I used  Start.cmd  as Administrator without modification apart from the SourcePath.

Edit 2:
Not sure if this is relevant but I ran .\Optimize-Offline.ps1 with just -SourcePath {mypath} and it completed successfully.

```
Exporting Windows 10 Pro using None compression.
Optimizing the Windows Media File Structure.
Finalizing Optimizations.
Optimize-Offline completed in [11] minutes with [0] errors. 

```

I ran it again with:

```
` .\Optimize-Offline.ps1 -SourcePath D:\winwork\183621.ISO -MetroApps 'Select' -SystemApps -Packages -Features -Registry -Win32Calc -Dedup -DaRT -Additional -ISO`
``` 
It failed as above.

Edit 3:

```
PS C:\Users\moxie> Get-Variable

Name                           Value
----                           -----
$                              OSCDIMG
?                              False
^                              OSCDIMG
ADK_ROOT                       {C:\Program Files (x86)\Windows Kits\10\, C:\Program Files (x86)\Windows Kits\10\}
```

**Comment by Aidolii** [comment]
I'm having this issue too.

**Comment by Aidolii** [comment]
@Radagast, I'm having this issue too. It seems it's being caused by the -ISO parameter. According to the documentation: `Using the -ISO switch will tell Optimize-Offline to automatically create a new Windows Installation Media ISO once all optimizations have been processed if the Windows ADK (Assessment and Deployment Kit) is installed on the system. If the Windows ADK is not installed on the system and the -ISO switch was used, a Windows Dialog Form will display allowing the end-user to select the oscdimg.exe premastering tool Optimize-Offline will use to create the bootable ISO.`

I have never installed the ADK, but it is possible something that Visual Studio 2019 downloaded is making it think that I did. I'm going to install the ADK and see if that doesn't remedy the situation. If it does, then it's likely @DrEmpiricism will need to make adjustments regarding the detection of ADK.

**Comment by Aidolii** [comment]
Well, shit, that didn't work. I installed the ADK's deployment tools, as it states it includes oscdimg:
![image](https://user-images.githubusercontent.com/37132025/59130807-19775100-8936-11e9-853e-75cc01ae5195.png)
However, I still run into the same error.

**Comment by Radagast** [comment]
@Aidolii 

The -ISO switch is definitely the issue, running without that seems to be fine. I just used ImgBurn to create the ISO. Just need to test it now...

**Comment by DrEmpiricism** [comment]
There are a lot of things in that first screenshot that are inconsistent with the latest version of the script.

First, it shows the ADK path variable as $ADK_ROOT, which is inaccurate.  The ADK path variable was changed to $ADKRoot the last update.  Second, the ADK root variable shows two entries which would mean it would have to query the registry twice to return two variables, and the script has never done that.

That means -FilePath was being passed an array that was also being joined with a relative path to the oscdimg.exe premastering tool (i.e. was not a valid absolute path), which would return a System.Object instead of a System.String value thus creating that error.

**Comment by Radagast** [comment]
@DrEmpiricism 

So the script I downloaded in the Optimize-Offline-master.zip from the project page is not the most recent?

**Comment by DrEmpiricism** [comment]
The .git link you provided has the latest version of the script, but the variable shown in your screenshot is not the variable in that latest version of the script. The master.zip will always have the latest files since I only push the latest builds to the master repository.

On a sidenote, the next script update should be coming tomorrow morning, and before I even saw this issue I had optimized the ISO creation process.  The update will also include some additional changes, too.

I still have not been able to produce any issue with ISO creation regardless if the Windows 10 ADK is installed or not.

**Comment by Radagast** [comment]
Trying again. I re-downloaded the zip and reinstalled ADK/rebooted. Powershell now looks like:

```
PS C:\Windows\system32> Get-Variable

Name                           Value
----                           -----
$
?                              True
^
args                           {}
ConfirmPreference              High
ConsoleFileName
DebugPreference                SilentlyContinue
Error                          {}
ErrorActionPreference          Continue
ErrorView                      NormalView
ExecutionContext               System.Management.Automation.EngineIntrinsics
false                          False
FormatEnumerationLimit         4
HOME                           C:\Users\moxie
Host                           System.Management.Automation.Internal.Host.InternalHost
InformationPreference          SilentlyContinue
input                          System.Collections.ArrayList+ArrayListEnumeratorSimple
MaximumAliasCount              4096
MaximumDriveCount              4096
MaximumErrorCount              256
MaximumFunctionCount           4096
MaximumHistoryCount            4096
MaximumVariableCount           4096
MyInvocation                   System.Management.Automation.InvocationInfo
NestedPromptLevel              0
null
OutputEncoding                 System.Text.ASCIIEncoding
PID                            7808
PROFILE                        C:\Users\moxie\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
ProgressPreference             Continue
PSBoundParameters              {}
PSCommandPath
PSCulture                      en-GB
PSDefaultParameterValues       {}
PSEdition                      Desktop
PSEmailServer
PSHOME                         C:\Windows\System32\WindowsPowerShell\v1.0
PSScriptRoot
PSSessionApplicationName       wsman
PSSessionConfigurationName     http://schemas.microsoft.com/powershell/Microsoft.PowerShell
PSSessionOption                System.Management.Automation.Remoting.PSSessionOption
PSUICulture                    en-US
PSVersionTable                 {PSVersion, PSEdition, PSCompatibleVersions, BuildVersion...}
PWD                            C:\Windows\system32
ShellId                        Microsoft.PowerShell
StackTrace
true                           True
VerbosePreference              SilentlyContinue
WarningPreference              Continue
WhatIfPreference               False

```

I'll update as I progress.

**Comment by Radagast** [comment]
I found the reason for the error, I had the incorrect ADK installed!. The base system is on 1803 and the ISO I'm trying to modify is 1903. the original ADK I downloaded was for 1903. Removed that and installed the version for 1803 and all seems well.

That said, I'm now seeing a different issue.

```
Get-WindowsCapability : The process cannot access the file because it is being used by another process.
At D:\winwork\Optimize-Offline.ps1:731 char:22
+     $GetCapability = Get-WindowsCapability -Path $MountFolder | Where ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
```
This has happened a couple of times. It simply stops and leaves the temporary folder created by OO in a state where I had reboot, take ownership and remove inheritance\permissions before I could remove it.

**Comment by Aidolii** [comment]
I'm on 1903 and I'm wanting to modify a 1903 ISO. I installed the 1903 ADK. Maybe the 1903 ADK is to blame?

**Comment by DrEmpiricism** [comment]
The build of the ADK was not the issue.  I personally have 1903 on my workstation and 1803 on my server and the script detects the ADK path and creates an ISO fine regardless which system I use.  Likewise, I know others who use the latest Insider Update ADKs and ADKs from 1607 without any issues.

> 
> ```
> Get-WindowsCapability : The process cannot access the file because it is being used by another process.
> At D:\winwork\Optimize-Offline.ps1:731 char:22
> +     $GetCapability = Get-WindowsCapability -Path $MountFolder | Where ...
> +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
>     + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
> ```
> 
> This has happened a couple of times. It simply stops and leaves the temporary folder created by OO in a state where I had reboot, take ownership and remove inheritance\permissions before I could remove it.

There is something else interacting with the mounted image when the script tries to query the capability packages and is not because of the script itself.

**Comment by Aidolii** [comment]
@DrEmpiricism I disagree with this issue being closed. The issue that you say where something is interacted with the mounted image isn't even the same problem as in the first post. I'm still having that issue.
