### ISSUE TITLE
Get-Item : Cannot bind argument to parameter 'LiteralPath' because it is null.

### ISSUE THREAD

**Issue by 1Some1one1** [DrEmpiricism/Optimize-Offline#86]
```
Get-Item : Cannot bind argument to parameter 'LiteralPath' because it is null.
At C:\Users\User\Documents\Optimize-Offline\Optimize-Offline.ps1:2442 char:46
+             $Oscdimg = Get-Item -LiteralPath (Get-Oscdimg) -Force -Er ...
+                                              ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Item], ParameterBindingVal 
   idationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M 
   icrosoft.PowerShell.Commands.GetItemCommand
 ```
Occurs with -ISO in latest commit.

**Comment by DrEmpiricism** [comment]
That error is because the path to the oscdimg tool does not exist.

Do you have the ADK installed?  If not, did you select an oscdimg path using the form that displays?

**Comment by 1Some1one1** [comment]
Components of the ADK were installed as dependencies to the Windows SDK automatically through Visual Studio 2019. The Deployment Tools were not installed along with them.

No form to select an alternate oscdimg.exe came up.

**Comment by 1Some1one1** [comment]
I managed to get this working by reverting the Oscdimg code to the June 5 version. The form came up and I selected my copy of oscdimg.exe

**Comment by DrEmpiricism** [comment]
Since the function returned a valid ADK path, it did not ask you to select an alternating path.  The form allowing for the selection of an alternative path only display when there is no ADK installed.

The reason the earlier version shows the pop-up is because the function tested if the the variable assigned to the path is valid as opposed to simply if it does not have a $null value.

When I modified that part of the script, I did not consider the fact that some ADK variants are installed with the Deployment Tools omitted.  In any case, I will re-add the full path testing.
