### ISSUE TITLE
Request to add 'Group name' to firewall rules

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#97]
Asking if you could add a group name like "Optimize-Offline" to the five firewall rules.
Makes it easier to use a filter in Window's built-in firewall.
Example:
_Now_: "New-NetFirewallRule -DisplayName "SmartScreen Inbound" -Action Block ...."
_Suggestion_: New-NetFirewallRule -DisplayName "SmartScreen Inbound"  -Group "Optimize-Offline" -Action Block ..."

**Comment by DrEmpiricism** [comment]
It's possible I will add Group Names but it's not as easy as entering it during the creation of a new firewall rule, as you cannot add a group name during the creation of a new firewall object.  Moreover, setting the group is not entirely as straight-forward as the PowerShell cmdlets lead one to believe but I do set Group Names on my server so doing it for the online script would not be a big deal. Frankly, I would have added specific Group Names if the rules that script added were in abundance but considering only a few get set, I did not see the point in doing so since I can't imaging it not being obvious which rules the script set.

**Comment by Phatastik** [comment]
No worries either way.

**Comment by MelkorLord** [comment]
@DrEmpiricism I see your point about the small amount of rules and it makes perfectly sense but I think the rationale lies elsewhere. To me at least, the good reason to use a `Group` name in the firewall rules is to visually separate the default Windows rules (or auto added by installing some random app) from the rules generated by a custom installation. This way in case of troubleshooting, it's easier to identify where the rule came from.

**Comment by Phatastik** [comment]
AKAIK, firewall rules are no longer included in this project.
